version: '3'
services:
  nginx:
    image: 'orthancteam/orthanc-nginx:24.5.1'
    depends_on:
      - orthanc
      - orthanc-auth-service
      - keycloak
    restart: unless-stopped
    ports:
      - '80:80'
    environment:
      ENABLE_ORTHANC: 'true'
      ENABLE_KEYCLOAK: 'true'
      ENABLE_ORTHANC_TOKEN_SERVICE: 'false'
      ENABLE_HTTPS: 'false'
      ENABLE_OHIF: 'true'
  orthanc:
    image: 'orthancteam/orthanc:24.5.1'
    volumes:
      - 'orthanc-storage:/var/lib/orthanc/db'
      - './orthanc-config.json:/etc/orthanc/orthanc-config.json'
    depends_on:
      - orthanc-db
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: 'true'
      DICOM_WEB_PLUGIN_ENABLED: 'true'
      ORTHANC__POSTGRESQL__HOST: orthanc-db
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: ReadCommitted
      VERBOSE_ENABLED: 'true'
      VERBOSE_STARTUP: 'true'
  orthanc-auth-service:
    image: 'orthancteam/orthanc-auth-service:24.5.1'
    volumes:
      - './permissions.jsonc:/orthanc_auth_service/permissions.json'
    depends_on:
      - keycloak
    restart: unless-stopped
    environment:
      SECRET_KEY: change-me-I-am-a-secret-key
      ENABLE_KEYCLOAK: 'true'
      PUBLIC_ORTHANC_ROOT: 'http://localhost/orthanc/'
      PUBLIC_LANDING_ROOT: 'http://localhost/orthanc/ui/app/token-landing.html'
      PUBLIC_OHIF_ROOT: 'http://localhost/orthanc/ohif/'
      USERS: |
        {
          "share-user": "change-me"
        }
  orthanc-db:
    image: 'postgres:14'
    restart: unless-stopped
    volumes:
      - 'orthanc-db:/var/lib/postgresql/data'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  ohif:
    image: 'orthancteam/ohif-v3:24.5.1'
    restart: unless-stopped
  keycloak:
    image: 'orthancteam/orthanc-keycloak:24.5.1'
    depends_on:
      - keycloak-db
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change-me
      KC_DB: postgres
      KC_DB_URL: 'jdbc:postgresql://keycloak-db:5432/keycloak'
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
  keycloak-db:
    image: 'postgres:14'
    restart: unless-stopped
    volumes:
      - 'keycloak-db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
volumes:
  orthanc-storage:
    driver: local
  orthanc-db:
    driver: local
  keycloak-db:
    driver: local
